
from typing import Any, Callable, Optional, Union
from typing import Protocol

from pathlib import Path


class BackendModule(Protocol):
    def init_datasetdict_from_disk(self, path: Union[str, Path]) -> Any: ...
    def download_datasetdict_from_hub(self, repo_id: str, local_dir: Union[str, Path]) -> str: ...
    def init_datasetdict_streaming_from_hub(self, repo_id: str) -> dict[str, Any]: ...
    def generate_datasetdict_to_disk(self, output_folder: Union[str, Path]) -> None: ...
    def push_local_datasetdict_to_hub(self, repo_id: str, local_dir: Union[str, Path]) -> None: ...
    def configure_dataset_card(self, repo_id: str, infos: dict) -> None: ...



