repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
        args: [ --fix ]
        exclude: ^(examples/)
      - id: ruff-format
        exclude: ^(examples/)
  
  - repo: local
    hooks:
      - id: run-pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        exclude: ^(examples/)

      - id: run-pytest
        name: pytest
        entry: pytest tests
        language: system
        types: [python]
        exclude: ^(examples/)
        pass_filenames: false