name: plaid

channels:
  - conda-forge
  - nodefaults

dependencies:
#---# basic python
  - pip
  - mamba
  - conda-pack
  - ipython
  - ipykernel
  - jupyter
  - jupyterlab
  - notebook
  # - sh
  - rich
  - python-dotenv
  - tqdm
  - setuptools
  - pybind11
  - pyyaml
  - scalene
#---# formatting
  - autopep8
  - black
  - yapf
#---# test
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  - mypy
  - pytest-mypy
  - types-setuptools
  - types-toml
#---# doc
  - sphinx
  - sphinx-autoapi
  - furo
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - sphinxcontrib-apidoc
  - myst-nb
  - myst-parser
  - pylint # to use https://pylint.readthedocs.io/en/latest/pyreverse.html
  - graphviz
  - pyment

#---# science
  - numpy
  - einops
  - scipy
#---# visu
  - matplotlib
  - seaborn
#---# mesh/graph libs
  - gmsh
  - python-gmsh
  - meshio
  - trimesh
  - networkx
  - basictools>=1.9.9
  - pyvista<=0.38
  - h5py
  - pycgns
