[tool.poetry]
name = "pyplaid"
version = "0.1.5"
description = "A package that implements a data model tailored for AI and ML in the context of physics problems"
authors = ["Safran <fabien.casenave@safrangroup.com>"]
license = "BSD-3-Clause"
readme = "README.md"
packages = [
    { include = "plaid", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
tqdm = "*"
pyyaml = "*"
pycgns-core = "*"
numpy = "*"
matplotlib-base = "*"
rich = "*"
scikit-learn = "*"
datasets = ">=3.0"
pydantic = "*"

[tool.poetry.group.dev.dependencies]
pre-commit = "*"
ruff = "*"
pytest = "*"
pytest-cov = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
myst-nb = "*"
myst-parser = "*"
furo = "*"
sphinx-autoapi = "*"
sphinx-tabs = "*"
sphinxcontrib-bibtex = "*"

[build-system]
requires = ["poetry"]