bridge:
  function:
    _target_: src.data.loader.bridges.elasto_plasto_dynamics.elasto_plasto_dynamics_sample_to_geometric
    _partial_: true
  data_info:
    name: 2d_elasto_plasto_dynamics
    geometry_dimension: 2
    input_field_dim: 7
    input_scalar_dim: 1
    output_field_dim: 2
    output_scalar_dim: 0
loader:
  _target_: src.data.loader.hub_loader.HubLoader
  bridge: ${bridge.function}
  dataset_name: PLAID-datasets/2D_ElastoPlastoDynamics
  cache_dir: cached_datasets/2D_ElastoPlastoDynamics
  task_split:
  - train
  - test
  processes_number: 1
scaler:
  _target_: src.data.scaler.StandardScaler
model:
  _target_: src.models.vits.flatformer_cls_less.FlatFormerCLSLess
  n_vertices_per_subdomain: 100
  n_head: 16
  dim_ff: 128
  num_layers: 2
  activation: gelu
  dropout: 0.1
  latent_dim: 256
  input_field_dim: ${bridge.data_info.input_field_dim}
  input_scalar_dim: ${bridge.data_info.input_scalar_dim}
  output_field_dim: ${bridge.data_info.output_field_dim}
  output_scalar_dim: ${bridge.data_info.output_scalar_dim}
  tokenizer:
    _target_: src.models.vits.tokenization.temporal_flatten_tokenizer.TemporalFlattenTokenizer
    partitioner:
      _target_: src.models.vits.tokenization.partitioners.metis_partitioner.MetisPartitioner
      processes_number: 1
      n_vertices_per_subdomain: ${model.n_vertices_per_subdomain}
      absolute_tol: 1
      relative_tol: 0.1
    tokenization_type: morton
    processes_number: 1
    output_field_dim: ${model.output_field_dim}
  preprocessing:
    train_seed: 270
    val_seed: 92
    test_seed: 42
score_fn:
  _target_: src.evaluation.score.compute_score
  _partial_: true
  base_name: null
training:
  lbda: 1
  test_size: 0.2
  batch_size: 500
  num_epochs: 50
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 1.0e-05
seed: 5
