global:
  dataset_path: "PLAID-datasets/VKI-LS59"
  save_path: "./artifacts"
  train_split_name: "train"
  test_split_name: "test"

input_scalar_scaler:
  scaler_type: "MinMaxScaler"
  feature_names:
    - angle_in
    - mach_out

output_scalar_scaler:
  scaler_type: "MinMaxScaler"
  feature_names:
    - Q
    - power
    - Pr
    - Tr
    - eth_is
    - angle_out

pca_nodes:
  base_name: Base_2_2
  field_name: nodes
  n_components: 3

pca_mach:
  base_name: Base_2_2
  field_name: mach
  n_components: 5

pca_nut:
  base_name: Base_2_2
  field_name: nut
  n_components: 8

regressor_mach:
  type: "GaussianProcessRegressor"
  options:
    kernel: Matern
    kernel_options:
      nu: 2.5
    optim: fmin_l_bfgs_b
    num_restarts: 2
    anisotropic: True
    random_state: 42
    show_warnings: False
  input:
    scalar_names:
      - angle_in
      - mach_out
    vector_names:
      - reduced_nodes
  output:
    vector_names:
      - reduced_mach