input_scalar_scaler:
  in_features_identifiers:
    - type: scalar
      name: angle_in
    - type: scalar
      name: mach_out

pca_nodes:
  in_features_identifiers:
    - type: nodes
      base_name: Base_2_2
  out_features_identifiers:
    - type: scalar
      name: reduced_nodes_*

pca_mach:
  in_features_identifiers:
    - type: field
      name: mach
      base_name: Base_2_2
  out_features_identifiers:
    - type: scalar
      name: reduced_mach_*

regressor_mach:
  in_features_identifiers:
    - type: scalar
      name: angle_in
    - type: scalar
      name: mach_out
    - type: scalar
      name: reduced_nodes_*
  out_features_identifiers:
    - type: scalar
      name: reduced_mach_*