name: plaid
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
#---# io
  - pyyaml
#---# SciML
  - scikit-learn
  - datasets >=3.0
  - numpy
  - matplotlib-base
#---# data validation
  - pydantic
#---# mesh/graph libs
  - muscat=2.4.1
  - pycgns-core
#---# doc
  - sphinx
  - sphinx-autoapi
  - sphinx-tabs
  - sphinxcontrib-bibtex
  - myst-nb
  - myst-parser
  - furo