name: Build wheel

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build wheels
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # fetch full history and tags

      - name: Install HDF5 dev libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build --wheel --outdir dist/

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: plaid-wheels
          path: dist/*.whl
