name: Documentation

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: false
          auto-activate-base: false
          miniforge-variant: Miniforge3

      - name: Create environment
        run: |
          conda create -n plaid-dev python=3.11 muscat=2.4.1 poetry
          conda run -n plaid-dev poetry install --with docs

      - name: Compile documentation
        run: |
          cd docs
          conda run -n plaid-dev bash generate_doc.sh