name: Documentation

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          activate-environment: plaid-dev
          channels: conda-forge, nodefaults
          channel-priority: strict
          miniforge-variant: Miniforge3
          auto-update-conda: true
          auto-activate-base: false
          use-mamba: false

      - name: Create environment
        run: |
          conda install -n plaid-dev -c conda-forge muscat=2.4.1 poetry
          conda run -n plaid-dev poetry install --with docs

      - name: Compile documentation
        run: |
          cd docs
          conda run -n plaid-dev bash generate_doc.sh