name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build:
    name: Build wheels with uv
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --dev

      - name: Build distribution
        run: uv build

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: sanity check
        run: echo "This job is only for publishing to PyPI."      
      # - uses: actions/checkout@v4

      # - name: Download all wheel artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     pattern: wheels-*
      #     path: dist
      #     merge-multiple: true

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     packages-dir: dist