name: Tests and Examples

permissions:
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

jobs:
  test:
    name: Run Tests and Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: plaid-dev
          channels: conda-forge
          channel-priority: strict
          miniforge-variant: Miniforge3
          auto-update-conda: true
          auto-activate-base: false
          use-mamba: false

      - name: Create environment
        run: |
          conda install -n plaid-dev -c conda-forge muscat=2.4.1 poetry
          poetry install

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          pytest tests --cov=src --cov-report=xml --cov-report=term

      - name: Run tests on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          pytest tests

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          pytest tests

      - name: Run examples on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd examples
          bash run_examples.sh

      - name: Run examples on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cd examples
          run_examples.bat

      - name: Upload coverage to Codecov (Linux only)
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          name: python-${{ matrix.python-version }}
          verbose: true

    #   - name: Set up Miniconda
    #     uses: conda-incubator/setup-miniconda@v2
    #     with:
    #       miniforge-variant: Miniforge3
    #       miniforge-version: latest
    #       use-mamba: true
    #       auto-activate-base: false
    #       auto-update-conda: true
    #       activate-environment: plaid_python${{ matrix.python-version }}
    #       environment-file: .github/workflows/conda_envs/python${{ matrix.python-version }}.yml